### ISSUE TITLE
running ver no longer works

### ISSUE THREAD

**Issue by the-j0k3r** [silverwind/versions#12] opened 2019-10-16 07:56 UTC
@silverwind following https://github.com/silverwind/ver/issues/10 I have now made some changes to Wikipedia Dark https://github.com/StylishThemes/Wikipedia-Dark/commits/master

@mottie

upon running `npm run patch` 

```log
 npm run patch

> wikipedia-dark@2.3.14 patch C:\Users\Joker\github\Wikipedia-Dark-Upstream
> ver -p patch wikipedia-dark.user.css


Microsoft Windows [Version 10.0.17134.1069]
```

No files are changed.

package-lock.json exists

reverting to ver @5.1.3 works

Ive tried:

removing node_modules
reinstalling via `npm i`
recloning
downgrading nodejs from 12.12.0 to 10.16.3 and retrying all the above
running command in powershell admin
running command via bash (MINGW64)

OS is Windows 10 pro 1803 build 17134.1069

edit also Microsoft Windows [Version 10.0.17134.1099]

**Comment by silverwind** [comment] 2019-10-16 10:20
Did you try 5.4.3? There was a important fix for projects with `package-lock.json`.

**Comment by the-j0k3r** [comment] 2019-10-16 10:50
yes, anything after 5.1.3 fails for me without output

**Comment by silverwind** [comment] 2019-10-16 11:25
Besides littering the code with `console.log`? Probably not. No output at all is very strange, you should at least get a error message, given that the whole app is wrapped in a `.catch` handler.

**Comment by the-j0k3r** [comment] 2019-10-16 11:28
>No output at all is very strange, you should at least get a error message, given that the whole app is wrapped in a .catch handler.

Should but dont

see 

![generic](https://user-images.githubusercontent.com/31389848/66915219-c797b380-f018-11e9-8716-32523f627946.gif)

same with bash MINGW64 and powershell, exact same

**Comment by silverwind** [comment] 2019-10-16 11:28
Does it work if you rename `package-lock.json`?

**Comment by the-j0k3r** [comment] 2019-10-16 11:31
rename/delete package-lock.json

![generic](https://user-images.githubusercontent.com/31389848/66915437-4a207300-f019-11e9-9d45-e4a03b4f5ccf.gif)

**Comment by silverwind** [comment] 2019-10-16 11:32
- clone the `ver` repo and run `npm install` in it
- run `node <path to ver.js> -p patch wikipedia-dark.user.css`

If that doesn't give you anything, start adding `console.log` to `ver.js` :)

**Comment by the-j0k3r** [comment] 2019-10-16 11:42
OK

 `node C:\Users\Joker\Desktop\ver\ver.js -p patch wikipedia-dark.user.css` works but

`node C:\Users\Joker\Desktop\ver\ver.js -p -C patch wikipedia-dark.user.css` 

outputs fatal: paths 'fix ...' with -a does not make sense

**Comment by silverwind** [comment] 2019-10-16 12:12
So you can nail it down to `-C`? I am aware that `-C` currently has issues and will fail at escaping some characters for the shell. I need to switch to using array-form arguments for `execa` to fix that.

If you want to find the specific commit when a issue was introduced, `git bisect` is very handy.

> also its been failing but bumping anyway

Yes, I noticed that too. I think better error handling and/or delaying those file writes should help with that.

**Comment by the-j0k3r** [comment] 2019-10-16 14:21
Well I already said that v5.1.3 works anything else newer doesnt, is that a good git bysect?

>So you can nail it down to -C?

Well I can say that without doing this `node C:\Users\Joker\Desktop\ver\ver.js -p patch wikipedia-dark.user.css` everytime is an actual success.

But sure -C conked out here too, the problem isnt -C the actual problem is the basic functionality no loger works for me without that long workaround. +(

**Comment by the-j0k3r** [comment] 2019-10-16 15:55
updated to ver 5.4.4 test. 

![generic](https://user-images.githubusercontent.com/31389848/66936012-4d2d5a80-f03d-11e9-89e6-78d5a7179183.gif)

Now here is the interesting part

* Deleted `package-lock.json` and `node_modules`
* Did NOT run `apm i`
* Ran `npm run patch` and low and behold the same exact thing happened as gif above
No installing anything no error just the same output even though node_modules isnt there.

**Comment by the-j0k3r** [comment] 2019-10-17 06:41
Same result as above on 
Windows 10 Enterprise Version 10.0.18362.356 
node v10.16.0
npm 6.12.0

**Comment by Mottie** [comment] 2019-10-17 13:00
So the problem is this line:

```js
await run(`git commit -a ${commitMsgString}`, {nocmd: true});
```

If the `commitMsgString` is multiple lines, I see this message when I run `ver` directly:

> fatal: paths 'Darken ...' with -a does not make sense

The "Darken" is from my last commit, and here is a console log of the `commitMsgString` (I'm not sure why it's going so far back in the history):

```
-m '2.3.16' -m '* Darken white background. Fixes #88 (Rob Garrison)
* Fix CodeMirror indention issue (Rob Garrison)
* international landig page fixes (the-j0k3r)
* global update ver (the-j0k3r)
* 2.3.15 (silverwind)
* fix table headers color (the-j0k3r)
* fix tmbox colors (the-j0k3r)
* fix tables border and bg color (the-j0k3r)
* brighten cbnnr-close (the-j0k3r)
* dont add borders to frameless elements (the-j0k3r)
* fix topic title bar (the-j0k3r)
* invert spech bubbles (the-j0k3r)
* fix tt background white (the-j0k3r)
* add chnagelog on bumping (the-j0k3r)
* remove npx (the-j0k3r)
* remove linux only commands that fail windows side (the-j0k3r)
* global update deps (the-j0k3r)
* 2.3.14 (Eddie James Carswell II)
* More minor fixes (Eddie James Carswell II)
* 2.3.13 (the-j0k3r)
* various fixes see description... (the-j0k3r)
* 2.3.12 (the-j0k3r)
* fix unstyled elemnets in ru wiki closes #87 (the-j0k3r)
* 2.3.11 (Eddie James Carswell II)
* Minor element fixes for mobile style (Eddie James Carswell II)
* sidebar section underline brightness fix (the-j0k3r)
* 2.3.10 (Eddie James Carswell II)
* Fix portlet link bullets, transparent bg for diffs (Eddie James Carswell II)
* prevent CRLF (the-j0k3r)
* 2.3.9 (Eddie James Carswell II)
* More fixes for wikiEd (Eddie James Carswell II)
* Minor fixes for ruwiki (Eddie James Carswell II)
* Consolidate diff colors, convert rgba to variables (Eddie James Carswell II)
* Fix Wikidata referenceview and kbd tags on mobile (Eddie James Carswell II)
* Move ScriptInstaller fixes (Eddie James Carswell II)
* 2.3.8 (the-j0k3r)
* fix bright headers in ru.wiki fixes #86 (the-j0k3r)
* Meta: Center README badges and add logo (Eddie James Carswell II)
* Meta: Add build status to README (Eddie James Carswell II)
* 2.3.7 (Eddie James Carswell II)
* Meta: Update devDependencies (Eddie James Carswell II)
* Restore heading colors for article assessment gadget (Eddie James Carswell II)
* Fixes for the score extension and ScriptInstaller (Eddie James Carswell II)
* Fixes for diff revision slider gadget, warning box color (Eddie James Carswell II)
* 2.3.6 (the-j0k3r)
* fix white table in ru wiki fixed #85 (the-j0k3r)
* 2.3.5 (Eddie James Carswell II)
* Fixes #84, plus other minor Wiktionary tweaks (Eddie James Carswell II)
* Move changes to correct style block :/ (Eddie James Carswell II)
* 2.3.4 (Eddie James Carswell II)
* Watchlist and recent changes fixes (Eddie James Carswell II)
* Fully fix #82, move flagged revs fix to main style (Eddie James Carswell II)
* 2.3.3 (Eddie James Carswell II)
* Minor fixes for Wiktionary, Wikinews, Wikivoyage, Wikispecies, and Incubator (Eddie James Carswell II)
* Fix white headbar in the search page (TotalCaesar659)
* 2.3.2 (Eddie James Carswell II)
* Fixes for Wikipedia landing page (Eddie James Carswell II)
* Convert black to var (Eddie James Carswell II)
* Palette tweaks, fix regex to match project landing pages (Eddie James Carswell II)
* fix regex (the-j0k3r)
* 2.3.1 (the-j0k3r)
* sidebar + color add fixes (the-j0k3r)
* fix ttps://www.wikipedia.org was all white (the-j0k3r)
* partially fix #82 (the-j0k3r)
* Meta: Updated readme with mobile screenshot, added badges (Eddie James Carswell II)
* 2.3.0 (Eddie James Carswell II)
* Sync ORES color changes, fixes for episode list tables (Eddie James Carswell II)
* Main page fixes for ruwiki (fixes #81) (Eddie James Carswell II)
* Merge branch '\''mobile-style'\'' (Eddie James Carswell II)
* Table color overrides, MathML and settings page fixes (Eddie James Carswell II)
* Reduce all borders to --gray-5 (Eddie James Carswell II)
* More polishing on mobile style (Eddie James Carswell II)
* Further element color fixes and general polish (Eddie James Carswell II)
* Cleanup: Combine selectors for duplicate declarations (Eddie James Carswell II)
* Fix diff colors (Eddie James Carswell II)
* Fix more article elements and templates (Eddie James Carswell II)
* Top bar icon tweaks (Eddie James Carswell II)
* Fixes for language picker and other article UI elements (Eddie James Carswell II)
* Color fixes for Watchlist (Eddie James Carswell II)
* Fixing broken element padding on RecentChanges (Eddie James Carswell II)
* More RecentChanges color fixes (Eddie James Carswell II)
* More ORES color fixes (Eddie James Carswell II)
* Begin dark theme skeleton for mobile style (Eddie James Carswell II)
* 2.2.17 (Eddie James Carswell II)
* Lots of cleanup and TLC, mostly on secondary sites (Eddie James Carswell II)'
```

**Comment by Mottie** [comment] 2019-10-17 13:08
Ahh, I didn't use `git fetch` to get all the previous tags; that's why the history is so long.

**Comment by silverwind** [comment] 2019-10-17 19:03
Will switch to array form args for git commands which should work better at handling such cases because the shell is not involved.

**Comment by silverwind** [comment] 2019-10-17 19:13
Actually, it appears neither `fetch` nor `pull` retrieve tags by default, so one has to do `git pull --tags` to get them. I never noticed this not being the default because I have a alias that includes `--tags` and I guess we have to recommend that for the changelog feature to work as expected.

**Comment by silverwind** [comment] 2019-10-19 17:31
Pushed ver@6 which uses array form for `git` commands which should work much better with the `-C` argument. Also the important commands are now always printed on the console, so even if they error, it should be visible why it failed.

I'm still contemplating whether `-C` should do a `git fetch --tags`.

**Comment by the-j0k3r** [comment] 2019-10-20 07:30
> I'm still contemplating whether `-C` should do a `git fetch --tags`.

I think it would be wiser rather than documenting the need for it, that way it works out of the box though I would document the addition.

My alias setup for fork origin/upstream sync also fetches tags automatically with `git fetch --tags`

**Comment by the-j0k3r** [comment] 2019-10-20 07:54
Test ver 6.0.0, no dice. its exactly as all previous attempts and documented in gifs and posts, going back to ver 5.1.3 works

and this is without `-C` switch, this is vanilla patch/minor/major without any switches including `-p` see https://github.com/silverwind/ver/issues/12#issuecomment-542770438

**Comment by silverwind** [comment] 2019-10-20 12:29
Can reproduce the issue with it only printing the `cmd` startup prompt, but no idea how to fix it. It's something about how npm installs/runs global script. Running `ver.cmd` seems to work however. Did not try `yarn` yet, maybe it does global scripts differently on Windows.

**Comment by the-j0k3r** [comment] 2019-10-20 12:31
I use `-NoLogo` for my powershell startup arg, but without theres no change, and bash MINGW64 also has same issues.

But why is it then that ver 5.1.3 bumping works and with 5.1.4 and newer doesnt?

**Comment by silverwind** [comment] 2019-10-20 12:40
> But why is it then that ver 5.1.3 bumping works and with 5.1.4 and newer doesn't?

I don't see that. For me, any version of `ver` does not work, but `ver.cmd` always works. I'd suggest checking `.npmrc` in your homedir and possibly deleting/moving `%APPDATA%/Roming/npm`, maybe your global modules are stale.

**Comment by the-j0k3r** [comment] 2019-10-20 13:18
> I'd suggest checking `.npmrc` in your homedir 

No `.npmrc` in your homedir in my homedir but in %APPDATA%/Roming/npm/etc has this content.

`python=C:\Users\Joker\.windows-build-tools\python27\python.exe`

> and possibly deleting/moving `%APPDATA%/Roming/npm`, maybe your global modules are stale
Yep thanks for that tip and done.

Sadly nothing changed.

Well I found out why I get this annoying MS ver string printed at the end `Microsoft Windows [Version 10.0.17134.1099]` ever since this issue manifested,
Seems that typing ver in the cmd prompt outputs this, but Ive no idea why it shows up in powershell.

Im thoroughly lost.

**Comment by silverwind** [comment] 2019-10-20 17:29
Ah, I see `ver` is actually a `cmd` builtin which takes precedence, lol. So I guess I chose a bad name for the module.

**Comment by the-j0k3r** [comment] 2019-10-21 05:56
> Ah, I see the `ver` command is actually a `cmd` builtin which takes precedence, lol. So I guess I chose a bad name for the module. Maybe try modifying your `PATH` so node modules comes first, thought I fear builtin's may always come first.

Like I said the issue wasnt there when ver was bumping OK. So maybe it will go back to normal when ver works again.

I feel withdrawal symptoms from not being able to use ver... lol

**Comment by Mottie** [comment] 2019-10-22 01:44
Wow, so weird.

In the wikipedia repo, if I add some console logs to `ver.js`:
- Use `npm run patch` does nothing. I believe the `ver` for Windows is run instead of this module.
- Use `node ./node_modules/ver/ver.js -p -C patch wikipedia-dark.user.css`, I see this error (again):

   ```
   Error: No replacement made in X:\Repos\+StylishThemes\Wikipedia-Dark\package-lock.json
        at updateFile (X:\Repos\+StylishThemes\Wikipedia-Dark\node_modules\ver\ver.js:185:11)
        at async main (X:\Repos\+StylishThemes\Wikipedia-Dark\node_modules\ver\ver.js:328:7)
   ```

  The `package.json` and the css files both have an updated version.

- If I comment out the package-lock section of the code and run `node ./node_modules....`, it works! But, I see this commit (Note: I DO have both the v.2.3.17 and v2.3.16 tags already included, visible using `gitk`).

    ```
    v2.3.18
        
        * Darken Russian headbar. Fixes #90 (Rob Garrison)
        * global: update deps (the-j0k3r)
        * 2.3.17 (Rob Garrison)
        * Meta: update dependencies (Rob Garrison)
        * Darken home page. Fixes #89 (Rob Garrison)
        * 2.3.16 (Rob Garrison)
        * Darken white background. Fixes #88 (Rob Garrison)
        * Fix CodeMirror indention issue (Rob Garrison)
        * international landig page fixes (the-j0k3r)
        * global update ver (the-j0k3r)
    ````

**Comment by the-j0k3r** [comment] 2019-10-22 08:38
Here is an actual representation between working node_modules and ver combination and broken
I think theres some actual dependency causing this rather than ver directly. But there was no way to see what changed in background.

Perhpas someone can actually spot something there that triggers some ahah! moment.

I created a branch for stackoverflow based on master and my local node_modules and package-lock.json, using ver 5.1.4 there works.

See https://github.com/StylishThemes/StackOverflow-Dark/commits/ver-working

then when running `npm run update` https://github.com/StylishThemes/StackOverflow-Dark/commit/c47d9523f5b6fe9cef6951e91c628690dca81756 after that ver `npx ver -p patch stackoverflow-dark.user.css` no longer works.

**Comment by silverwind** [comment] 2019-10-22 10:24
@Mottie can you check if your `package-lock.json` actually contains a version string? Mine generated via npm 6.12.0 sure does:

```
$ head package-lock.json
{
  "name": "wikipedia-dark",
  "version": "2.3.19",
```

I see a few improvements to make:

- rename module or export additional binary name
- ignore replacement failures on `package-lock.json` as some versions of that file may not contain a version apparently.
- do file changes atomically and revert them if a `git` command fails

**Comment by Mottie** [comment] 2019-10-22 11:26
> your `package-lock.json` actually contains a version string

Yes, it does

```js
{
  "name": "wikipedia-dark",
  "version": "2.3.18",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {...}
  }
}
```

I think it's because I removed the v2.3.18 tag and did a hard reset to test, but because the `package-lock.json` is in `.gitignore`, it touch that file; so it was already 2.3.18.

**Comment by Mottie** [comment] 2019-10-22 11:39
I just used `node ./node_modules/ver/ver.js -p -C patch wikipedia-dark.user.css` for `v2.3.19` and it worked, except for including a commit history going back to `v2.3.15`.

**Comment by silverwind** [comment] 2019-10-22 13:34
Does `git tag` show the tags inbetween? If yes, what about `git show v2.3.18 --`?

**Comment by silverwind** [comment] 2019-10-22 13:39
> I think it's because I removed the v2.3.18 tag and did a hard reset to test, but because the package-lock.json is in .gitignore, the reset didn't touch that file; so it was already 2.3.18.

Replacement in `package-lock.json` is actually done via JSON.parse + JSON.stringify, so it's very weird that that failed. Will try to debug this later.

**Comment by Mottie** [comment] 2019-10-22 22:23
> Does `git tag` show the tags inbetween

```
v2.3.0
v2.3.1
v2.3.10
v2.3.11
v2.3.12
v2.3.13
v2.3.14
v2.3.15
v2.3.16
v2.3.17
v2.3.18
v2.3.19
v2.3.2
v2.3.3
v2.3.4
v2.3.6
v2.3.7
v2.3.9
```

> what about `git show v2.3.18 --`

```
> git show v2.3.18 --
commit a60d3527729b39a57824e9df238ef0a1f5399d75 (tag: v2.3.18)
Author: Rob Garrison <wowmotty@gmail.com>
Date:   2019-10-21

    2.3.18

diff --git a/package.json b/package.json
index af77c23..bf13e3c 100644
--- a/package.json
+++ b/package.json
@@ -1,7 +1,7 @@
 {
   "name": "wikipedia-dark",
   "title": "Wikipedia Dark",
-  "version": "2.3.17",
+  "version": "2.3.18",
   "description": "Wikipedia Dark theme",
   "license": "CC-BY-SA-4.0",
   "repository": "https://github.com/StylishThemes/Wikipedia-Dark",
diff --git a/wikipedia-dark.user.css b/wikipedia-dark.user.css
index 86adb67..6fa34dc 100644
--- a/wikipedia-dark.user.css
+++ b/wikipedia-dark.user.css
@@ -1,7 +1,7 @@
 /* ==UserStyle==
 @name         Wikipedia Dark
 @namespace    StylishThemes
-@version      2.3.17
+@version      2.3.18
 @description  Wikipedia Dark theme
 @author       StylishThemes
 @homepageURL  https://github.com/StylishThemes/Wikipedia-Dark
```

**Comment by the-j0k3r** [comment] 2019-10-23 06:21
6.0.1 still no dice with basic functionality.

**Comment by the-j0k3r** [comment] 2019-10-24 13:41
I would like to re-iterate https://github.com/silverwind/ver/issues/12#issuecomment-544861035 and that Im currently ignoring the -C functionality altogether, I originally mentioned it due to being the only error I had when reporting this.

The only repo I have ver working is stackoveflow dark any upgrades of deps will break that also like everywhere else deps have been upgraded.

**Comment by the-j0k3r** [comment] 2019-10-29 09:53
6.0.2 still no joy, and again without -C

`ver -p -d patch github-dark.css github-dark.user.css`

**Comment by the-j0k3r** [comment] 2019-10-30 09:03
Ok I now find per above that installing ver globally works and I think I know why.

See the difference in packages in `node_modules\ver\node_modules` between global and local.

```log
~\AppData\Roaming\npm\node_modules\ver\node_modules> dir

    Directory: C:\Users\Joker\AppData\Roaming\npm\node_modules\ver\node_modules

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       29/10/2019     09:59                .bin
d-----       29/10/2019     09:59                @nodelib
d-----       29/10/2019     09:59                braces
d-----       29/10/2019     09:59                cross-spawn
d-----       29/10/2019     09:59                end-of-stream
d-----       29/10/2019     09:59                execa
d-----       29/10/2019     09:59                fast-glob
d-----       29/10/2019     09:59                fastq
d-----       29/10/2019     09:59                fill-range
d-----       29/10/2019     09:59                find-up
d-----       29/10/2019     09:59                get-stream
d-----       29/10/2019     09:59                glob-parent
d-----       29/10/2019     09:59                human-signals
d-----       29/10/2019     09:59                is-extglob
d-----       29/10/2019     09:59                is-glob
d-----       29/10/2019     09:59                is-number
d-----       29/10/2019     09:59                is-stream
d-----       29/10/2019     09:59                isexe
d-----       29/10/2019     09:59                locate-path
d-----       29/10/2019     09:59                merge-stream
d-----       29/10/2019     09:59                merge2
d-----       29/10/2019     09:59                micromatch
d-----       29/10/2019     09:59                mimic-fn
d-----       29/10/2019     09:59                minimist
d-----       29/10/2019     09:59                npm-run-path
d-----       29/10/2019     09:59                once
d-----       29/10/2019     09:59                onetime
d-----       29/10/2019     09:59                p-finally
d-----       29/10/2019     09:59                p-limit
d-----       29/10/2019     09:59                p-locate
d-----       29/10/2019     09:59                p-try
d-----       29/10/2019     09:59                path-exists
d-----       29/10/2019     09:59                path-key
d-----       29/10/2019     09:59                picomatch
d-----       29/10/2019     09:59                pump
d-----       29/10/2019     09:59                reusify
d-----       29/10/2019     09:59                run-parallel
d-----       29/10/2019     09:59                semver
d-----       29/10/2019     09:59                shebang-command
d-----       29/10/2019     09:59                shebang-regex
d-----       29/10/2019     09:59                signal-exit
d-----       29/10/2019     09:59                strip-final-newline
d-----       29/10/2019     09:59                to-regex-range
d-----       29/10/2019     09:59                which
d-----       29/10/2019     09:59                wrappy

~\AppData\Roaming\npm\node_modules\ver\node_modules>
```

In the GitHub Dark clone of master

```log
~\github\GitHub-Dark-Upstream\node_modules\ver\node_modules [master ≡]> dir


    Directory: C:\Users\Joker\github\GitHub-Dark-Upstream\node_modules\ver\node_modules


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       30/10/2019     07:57                @nodelib
d-----       30/10/2019     07:57                fast-glob
d-----       30/10/2019     07:57                find-up
d-----       30/10/2019     07:57                locate-path
d-----       30/10/2019     07:57                minimist
d-----       30/10/2019     07:57                p-limit
d-----       30/10/2019     07:57                p-locate
d-----       30/10/2019     07:57                p-try
d-----       30/10/2019     07:57                path-exists
```

Next test, 

1) copy global `node_modules\ver\node_modules` into the GitHub Dark `node_modules\ver\node_modules`
2) run `grunt patch`

Result **no change**. ver STILL wont run locally even without `-C` and globally with `-C` still outputs wrong changelog messages and wrong commit hash.

I wonder if this is actually npm related as well. Seems Weird to just have stopped working.

**Comment by the-j0k3r** [comment] 2019-10-30 10:40
OK this is almost definitely npm related.

I managed to get it to work.

Started with no global packages.

1) Install nodejs 10.6.0
2) in GitHub Dark `npm i`
3) in terminal `npm i grunt grunt-cli -g`
4) run grunt patch 

## SUCCESS, sort of

Why must grunt and grunt-cli be global?

nodejs 12 and 13 fail did not try nodejs 11 and no way I know of to troubleshoot npm node/ issues but this is the closest Ive come.

**Comment by the-j0k3r** [comment] 2019-11-01 09:08
Had to upgrade nodejs from 10.6.0 to 12.0.0  because running generate doesnt work, suprisingly this keeps ver in a semi working state with the caveats as above.

**Comment by the-j0k3r** [comment] 2019-11-03 09:28
> I guess its a workaround the issue.

the workaround works in GitHub Dark due to grunt, else needs ver globally installed for npm only repos.

**Comment by AfroThundr3007730** [comment] 2019-11-03 20:28
I haven't really had problems with ver on my end, but I'm running Debian so that's probably why.

**Comment by xt0rted** [comment] 2019-11-04 06:38
I was just trying to do a new release for [GitHub-Selected-Tab-Color](https://github.com/StylishThemes/GitHub-Selected-Tab-Color) and fell on my face because of this. `ver` no longer works for me, even rolling back to 4.3.0 which was used the last time I did a release in this repo.

The script here is even simpler than the ones being discussed, it's only `ver -p patch github-selected-tab-color.user.css`. In order to do the release I had to run:

```console
.\node_modules\.bin\ver.cmd -p patch github-selected-tab-color.user.css
```

**Comment by silverwind** [comment] 2019-11-18 18:19
I renamed the package to `versions` to resolve the clash with Windows builtin `ver`. Installing `ver` will now give a deprecation warning.

**Comment by the-j0k3r** [comment] 2019-11-18 19:33
I also found out that, if you install npx globally bumping works again, and of course re-adding npx to all repos is also necessary.

So you need, grunt, grunt-cli and npm globally installed in order to run this say in GitHub Dark Windows side.

**Comment by xt0rted** [comment] 2019-11-18 19:55
If you add `"patch": "grunt patch"` to the npm scripts you can do a release with `npm run patch`. There's no need to install anything globally (I just tried this on windows and it worked). All of these should probably be added anyhow since we were trying to move away from grunt and having them there will make it easier to migrate one task at a time.

The only part of my test that didn't work as expected was creating the tag, that still happened on the commit before the release.

```
C:\dev\GitHub\GitHub-Dark [master ≡]> git reflog 
8440cde HEAD@{2}: commit: v1.22.139
3818d16 HEAD@{3}: commit: Update package.json

C:\dev\GitHub\GitHub-Dark [master ≡]> git tag -d v1.22.139
Deleted tag 'v1.22.139' (was 38969bb)  
```

**Comment by the-j0k3r** [comment] 2019-11-18 20:03
> The only part of my test that didn't work as expected was creating the tag, that still happened on the commit before the release.

thats was fixed, ver needs to be updated in package.json

> If you add `"patch": "grunt patch"` to the npm scripts you can do a release with `npm run patch`. There's no need to install anything globally (I just tried this on windows and it worked). All of these should probably be added anyhow since we were trying to move away from grunt and having them there will make it easier to migrate one task at a time.

well thats another way to do it, but I dont want to be adding grunt to repos that dont have it to fix a Windows/ Ver/npm issue in order to be able to works as before.

**Comment by xt0rted** [comment] 2019-11-18 20:16
@silverwind updated `ver` in the GHD repo before my test, so that was done using 7.0.1 of `versions`.

> I dont want to be adding grunt to repos that dont have it

I'm not saying install grunt in the other repos, just that if you're using npm scripts you don't need to install the tools globally. Nor do you need npx.

In GHD you can also use the script `"patch": "versions -p -d -C patch github-dark.css github-dark.user.css"` and then grunt isn't needed at all for this one (which is what the other repos are doing).

**Comment by silverwind** [comment] 2019-11-18 20:19
Yes, grunt is not needed and should be removed for simple tasks like that. I think there was actually a PR that did that.

BTW you can run scripts without `npx`, just run `node node_modules/.bin/versions`. That's how we did things before there was `npx` :)

**Comment by the-j0k3r** [comment] 2019-11-18 20:23
Thats just silly too =)

**Comment by silverwind** [comment] 2019-11-21 20:20
I don't think there's anything left to do here, so let's close it. If there is, open new issues.

**Closed by silverwind** 2019-11-21 20:20 UTC
